- id: prettier
  name: apply prettier
  description: apply prettier to js,jsx,md,html,json,yaml files
  language: node
  entry: prettier --write
  types: [js,jsx,md,html,json,yaml]
- id: prettier-java
  name: apply prettier-java
  description: apply prettier to java files
  language: node
  entry: prettier --write
  types: [java]
