- id: prettier
  name: apply prettier to js,jsx,md,html,json,yaml files
  language: node
  entry: prettier --write "**/*.{js,jsx,md,html,json.,yaml}"
- id: prettier-java
  name: apply prettier to java files
  language: node
  entry: prettier --write "**/*.{java}"
