- id: prettier-web
  name: apply prettier to web files
  description: apply prettier to Javascript, jsx, JSON, CSS, and HTML files
  stages: [pre-commit, manual]
  language: node
  entry: prettier --write
  exclude: ^.+\.(xctestplan|ipynb)$
  types_or: [javascript, jsx, json, html, css]
- id: prettier-docs
  name: apply prettier to documentation
  description: apply prettier to Javascript, jsx, Markdown, HTML, JSON, YAML files
  stages: [pre-commit, manual]
  language: node
  entry: prettier --write
  types_or: [markdown]
- id: prettier-java
  name: apply prettier-java
  description: apply prettier to Java files
  stages: [pre-commit, manual]
  language: node
  entry: prettier --plugin=prettier-plugin-java --plugin=prettier-plugin-properties --write
  types_or: [java, java-properties]
- id: prettier-config
  name: apply prettier to settings
  description: apply prettier to properties and xml files
  stages: [pre-commit, manual]
  language: node
  entry: prettier --plugin=@prettier/plugin-xml --plugin=prettier-plugin-properties --write
  types_or: [java-properties, xml, yaml]
